language: python
sudo: required
python:
  - "3.6"
install:
  - pip install -U codeclimate-test-reporter pipenv
  - pipenv install --dev
  - pip install -I "coverage>4.0,<4.4"
script:
  - PYTHONPATH=. py.test
after_success:
  - CODECLIMATE_REPO_TOKEN=614b3655ef4b6ac2082ebcb71642f0b7ad24ca6d6c3f661b20d3b4b2f2737966 codeclimate-test-reporter
